--Find the total sales generated by each customer.

Select	
	CustomerID,
	sum (Sales) as TotalSales
from Sales.Orders
group by  CustomerID

--Find the average sales per customer.

Select	
	CustomerID,
	sum (Sales) as TotalSales,
	AVG(Sales) as avgSales
from Sales.Orders
group by  CustomerID


--Find customers who have placed more than 5 orders.

SELECT
    CustomerID,
    COUNT(OrderID) AS TotalOrders
FROM Sales.Orders
GROUP BY CustomerID
HAVING COUNT(OrderID) > 2;

--Show orders where the sales amount
--is greater than the average sales amount of all orders
SELECT
    OrderID,
    CustomerID,
    Sales
FROM Sales.Orders
WHERE Sales > (
    SELECT AVG(Sales)
    FROM Sales.Orders
);

select avg (Sales) from Sales.Orders

--Display each customer's total sales
--and show only those customers 
--whose total sales are above the average customer sales.
SELECT
    CustomerID,
    SUM(Sales) AS TotalSales
FROM Sales.Orders
GROUP BY CustomerID
HAVING SUM(Sales) >
(
    SELECT AVG(CustomerSales)
    FROM
    (
        SELECT
            CustomerID,
            SUM(Sales) AS CustomerSales
        FROM Sales.Orders
        GROUP BY CustomerID
    ) T
);

--Find the salesperson who generated the highest total sales amount.

Select top 1
	SalesPersonID,
	sum (Sales) as totalsales
from Sales.Orders
group by SalesPersonID 
order by SUM(Sales) desc
